### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Tokiwa-17** [Tokiwa-17/cse230#5]
## UI 
- [ ] add menu page
## Implementation
- [ ] support multiple players
- [ ] AI Agent
- [ ] difficulty levels (change speed)
- [ ] sound Effects
